#!/bin/sh

set -e

BINARIES='ps free pgrep pmap pwdx skill slabtop tload uptime vmstat w watch pkill snice'

for bin in $BINARIES ; do \
    $bin --version | egrep "^$bin from procps-ng [0-9.]+$" ; \
done

